#!/bin/sh

. network.config
. redes_up.sh
. sgroutes

echo 1 > /proc/sys/net/ipv4/ip_dynaddr
echo 1 > /proc/sys/net/ipv4/ip_forward
echo 1 > /proc/sys/net/ipv4/tcp_syncookies

#modprobe ip_tables
modprobe ip_gre
modprobe ip_nat_pptp
modprobe ip_conntrack_pptp
modprobe ip_conntrack_ftp
modprobe ip_conntrack
modprobe ip_nat_ftp
#modprobe ip_conntrack_sip
#modprobe ip_nat_sip
#modprobe ip_conntrack_h323
#modprobe ip_nat_h323

SQUIDPORT=3128
SSLPORT=3128
SISPATH="/var/www/sistemas/bin/"
IPTABLES=`which iptables`
IPTABLES="$IPTABLES -w"
export IPTABLES SISPATH

echo "Limpando as cadeias..."
#/usr/sbin/conntrack -F
$IPTABLES -F
$IPTABLES -Z
$IPTABLES -X
$IPTABLES -t nat -F
$IPTABLES -t nat -Z
$IPTABLES -t nat -X
$IPTABLES -t mangle -F
$IPTABLES -t mangle -Z
$IPTABLES -t mangle -X

echo "Mascarando conexoes saida..."
. snat_uol.sh
. snat.sh
. masq.sh

echo "Bloqueando ataques conhecidos..."
for i in $(cat $SISPATH/links)
do
   $IPTABLES -A FORWARD -o ${!i} -p tcp --dport 445 -j DROP
   $IPTABLES -A FORWARD -o ${!i} -p udp --dport 445 -j DROP
   $IPTABLES -A INPUT -i ${!i} -p tcp --dport 3128:3129 -j DROP
done

echo "Mantendo conexoes existentes ..."
$IPTABLES -t filter -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
$IPTABLES -t filter -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT

echo "Criando cadeias de portas altas e baixas"
$IPTABLES -t filter -N LOWPORTS
$IPTABLES -t filter -N HIGHPORTS
$IPTABLES -t filter -A LOWPORTS -p tcp --dport :1023 -j ACCEPT
$IPTABLES -t filter -A LOWPORTS -p udp --dport :1023 -j ACCEPT
$IPTABLES -t filter -A LOWPORTS -p icmp -j ACCEPT
$IPTABLES -t filter -A HIGHPORTS -p tcp --dport 1024: -j ACCEPT
$IPTABLES -t filter -A HIGHPORTS -p udp --dport 1024: -j ACCEPT

echo "Liberando conexao local..."
$IPTABLES -t filter -A INPUT -p icmp -j ACCEPT
$IPTABLES -t filter -A INPUT -i lo -j ACCEPT

echo "Fixando links pelas portas..."
$IPTABLES -t mangle -A OUTPUT -m state --state ESTABLISHED,RELATED -j CONNMARK --restore-mark
$IPTABLES -t mangle -A PREROUTING -m state --state ESTABLISHED,RELATED -j CONNMARK --restore-mark
. connmark.sh
. mark.sh

echo "Capturando conversas do Jabber..."
$IPTABLES -t nat -A PREROUTING -p tcp --dport 6222 -j REDIRECT --to-ports 16667

echo "Levantando regras dinamicas..."
echo " - Whitelist IPs"
$IPTABLES -t filter -A FORWARD -m set --match-set whitelist src -j ACCEPT
$IPTABLES -t filter -A FORWARD -m set --match-set whitelist dst -j ACCEPT
$IPTABLES -t nat -A PREROUTING -m set --match-set whitelist src -j ACCEPT
$IPTABLES -t nat -A PREROUTING -m set --match-set whitelist dst -j ACCEPT

echo " - IPs bloqueados"
$IPTABLES -t filter -I INPUT -m set --match-set block src -j DROP
$IPTABLES -t filter -I FORWARD -m set --match-set block src -j DROP

echo " - GeoIP"
for i in $(cat $SISPATH/links)
do
   for g in $(cat /etc/sgipset/geoip); do
      $IPTABLES -t filter -A FORWARD -i ${!i} -m set --match-set geoip-$g src -j ACCEPT
   done
   $IPTABLES -t filter -A FORWARD -i ${!i} -m set --match-set geoip-nozone src -j ACCEPT
   $IPTABLES -t filter -A FORWARD -i ${!i} -j DROP
done

echo " - Liberação Amazonaws"
$IPTABLES -t filter -A FORWARD -m set --match-set amazon dst -p tcp --dport 443 -j ACCEPT
$IPTABLES -t nat -A PREROUTING -m set --match-set amazon dst -p tcp --dport 443 -j ACCEPT

echo " - Portas abertas"
. openports.sh
echo " - NAT"
. nat.sh
echo " - Bypass"
. bypass.sh
echo " - Bloqueios ao SMTP"
$IPTABLES -A FORWARD -p tcp --dport 25 -j LOG --log-level 1 --log-prefix 'SMTP: '
$IPTABLES -A FORWARD -p tcp --dport 26 -j LOG --log-level 1 --log-prefix 'SMTP: '
$IPTABLES -A FORWARD -p tcp --dport 465 -j LOG --log-level 1 --log-prefix 'SMTP: '
$IPTABLES -A FORWARD -p tcp --dport 587 -j LOG --log-level 1 --log-prefix 'SMTP: '
$IPTABLES -A FORWARD -p tcp -m multiport --dport 25,26,465,587 -j DROP
echo " - VPN"
. vpn.sh

echo " - Acessos ao MSN"
$IPTABLES -t nat -N MSN-pre
$IPTABLES -t filter -N MSN-fw
$IPTABLES -t nat -A MSN-pre -m set --match-set msn dst,dst -j ACCEPT
$IPTABLES -t filter -A MSN-fw -m set --match-set msn dst,dst -j ACCEPT
$IPTABLES -t nat -A PREROUTING -m set --match-set msn-hosts src -j MSN-pre
$IPTABLES -t filter -A FORWARD -m set --match-set msn-hosts src -j MSN-fw
$IPTABLES -A FORWARD -p tcp --dport 1863 -j LOG --log-level 1 --log-prefix 'MSN: '
$IPTABLES -A FORWARD -i $LAN_IF1 -p tcp --dport 1863 -j DROP

echo " - Portas proxy desviadas"
for i in $(cat $SISPATH/lans)
do
$IPTABLES -t nat -A PREROUTING -i ${!i} -p tcp -m set --match-set proxy dst -j REDIRECT --to-port $SQUIDPORT
$IPTABLES -t nat -A PREROUTING -i ${!i} -p tcp -m set --match-set proxy-ssl dst -j REDIRECT --to-port $SSLPORT
done

echo " - Liberacao ranges dinamicos"
$IPTABLES -t filter -A INPUT -m set --match-set range src -j OPENPORTS

echo " - Liberacao hosts da rede"
$IPTABLES -t filter -A INPUT -m set --match-set hosts src -j OPENPORTS
for i in $(cat $SISPATH/links)
do
$IPTABLES -t filter -A FORWARD -o ${!i} -m set --match-set hosts-low src -j LOWPORTS
$IPTABLES -t filter -A FORWARD -o ${!i} -m set --match-set hosts-high src -j HIGHPORTS
done
$IPTABLES -t filter -A INPUT -m set --match-set subnets src -j REJECT --reject-with icmp-host-prohibited

echo "Bloqueando todo o resto!!!"
$IPTABLES -t filter -A INPUT -j REJECT --reject-with icmp-host-prohibited
for i in $(cat $SISPATH/links)
do
   $IPTABLES -t filter -A FORWARD -o ${!i} -j REJECT --reject-with icmp-host-prohibited
done
