#!/bin/sh

IPSET=`which ipset`

. sgipset.hosts
. sgipset.subnets
. sgipset.msn
. sgipset.block
. sgipset.range
. sgipset.proxy
. sgipset.tor

echo "IPs externos liberados sem restrições"
$IPSET -exist create whitelist hash:net
$IPSET flush whitelist
for i in $(cat /etc/sgipset/whitelist); do $IPSET add whitelist $i; done

cd /etc/sgipset
rm -fR *-aggregated.zone
for g in $(cat geoip); do
        wget http://www.ipdeny.com/ipblocks/data/aggregated/$g-aggregated.zone
        $IPSET -exist create geoip-$g hash:net
        $IPSET flush geoip-$g
        for i in $(cat $g-aggregated.zone); do $IPSET add geoip-$g $i; done
done

$IPSET -exist create geoip-nozone hash:net
$IPSET flush geoip-nozone
for i in $(cat /etc/sgipset/nozone.zone); do $IPSET add geoip-nozone $i; done
